export default [
  //Ores
  {
    name: 'Gold Ore',
    description: 'A precious metal.',
    health: 48,
    colour: 'darkgoldenrod',
    material: 'shiny',
    probability: 5,
    type: 'block',
    category: 'ore',
    output: 'Gold Ingot',
    model: 'rock',
    locations: ['sandybeach'],
    tools: ['pickaxe'],
  },
  {
    name: 'Stone',
    description: 'A common material.',
    health: 24,
    colour: 'gray',
    material: 'matte',
    probability: 80,
    type: 'block',
    model: 'stone',
    locations: ['sandybeach'],
    tools: ['pickaxe'],
  },
  {
    name: 'Iron Ore',
    description: 'A less common metal.',
    health: 36,
    colour: 'slategray',
    material: 'shiny',
    probability: 50,
    type: 'block',
    category: 'ore',
    output: 'Iron Ingot',
    model: 'rock',
    locations: ['sandybeach'],
    tools: ['pickaxe'],
  },
  {
    name: 'Diamond',
    description: 'A very rare gem.',
    health: 80,
    colour: '#ACDDE7',
    material: 'glass',
    probability: 0.1,
    type: 'block',
    model: 'rock',
    locations: ['sandybeach'],
    tools: ['pickaxe'],
  },
  {
    name: 'Wood',
    description: 'A common material.',
    health: 12,
    colour: '#5e4328',
    material: 'matte',
    probability: 60,
    type: 'block',
    model: 'wood',
    locations: ['foggyforest'],
    tools: ['axe'],
  },
  {
    name: 'Coal',
    description: 'A common fuel.',
    health: 20,
    colour: '#2C4251',
    material: 'matte',
    probability: 30,
    type: 'block',
    category: 'fuel',
    model: 'rock',
    locations: ['sandybeach'],
    tools: ['pickaxe'],
  },
  //Tools
  {
    name: 'Wood Pickaxe',
    description: 'Mines stone fast.',
    recipe: { Stick: 2, Wood: 10 },
    strength: 1,
    efficiency: 2,
    health: 100,
    type: 'tool',
    colour: '#4A4138',
    material: 'matte',
    category: 'pickaxe',
  },
  {
    name: 'Stone Pickaxe',
    description: 'Mines stone faster.',
    recipe: { Stick: 2, Stone: 10 },
    strength: 1.25,
    efficiency: 3,
    health: 100,
    type: 'tool',
    colour: 'gray',
    material: 'matte',
    category: 'pickaxe',
  },
  {
    name: 'Iron Pickaxe',
    description: 'Mines stone even faster.',
    recipe: { Stick: 2, 'Iron Ingot': 10 },
    strength: 2,
    efficiency: 4,
    health: 200,
    type: 'tool',
    colour: 'slategray',
    material: 'shiny',
    category: 'pickaxe',
  },
  {
    name: 'Gold Pickaxe',
    description: 'Mines stone super fast.',
    recipe: { Stick: 2, 'Gold Ingot': 10 },
    strength: 3,
    efficiency: 6,
    health: 150,
    type: 'tool',
    colour: 'darkgoldenrod',
    material: 'shiny',
    category: 'pickaxe',
  },
  {
    name: 'Diamond Pickaxe',
    description: 'Mines stone very fast.',
    recipe: { Stick: 2, Diamond: 10 },
    strength: 5,
    efficiency: 8,
    health: 250,
    type: 'tool',
    colour: '#ACDDE7',
    material: 'glass',
    category: 'pickaxe',
  },
  {
    name: 'Wood Axe',
    description: 'Gathers wood fast.',
    recipe: { Stick: 2, Wood: 7 },
    strength: 1,
    efficiency: 2,
    health: 100,
    type: 'tool',
    colour: '#4A4138',
    material: 'matte',
    category: 'axe',
  },
  {
    name: 'Stone Axe',
    description: 'Gathers wood faster.',
    recipe: { Stick: 2, Stone: 7 },
    strength: 1.25,
    efficiency: 3,
    health: 100,
    type: 'tool',
    colour: 'gray',
    material: 'matte',
    category: 'axe',
  },
  {
    name: 'Iron Axe',
    description: 'Gathers wood even faster.',
    recipe: { Stick: 2, 'Iron Ingot': 7 },
    strength: 2,
    efficiency: 4,
    health: 200,
    type: 'tool',
    colour: 'slategray',
    material: 'shiny',
    category: 'axe',
  },
  {
    name: 'Gold Axe',
    description: 'Gathers wood super fast.',
    recipe: { Stick: 2, 'Gold Ingot': 7 },
    strength: 3,
    efficiency: 6,
    health: 150,
    type: 'tool',
    colour: 'darkgoldenrod',
    material: 'shiny',
    category: 'axe',
  },
  {
    name: 'Diamond Axe',
    description: 'Gathers wood very fast.',
    recipe: { Stick: 2, Diamond: 7 },
    strength: 5,
    efficiency: 8,
    health: 250,
    type: 'tool',
    colour: '#ACDDE7',
    material: 'glass',
    category: 'axe',
  },
  //Resources
  {
    name: 'Stick',
    description: 'Useful for crafting.',
    recipe: { Wood: 5 },
    type: 'resource',
  },
  {
    name: 'Gold Ingot',
    description: 'Pure bar of gold.',
    type: 'resource',
  },
  {
    name: 'Iron Ingot',
    description: 'Pure bar of iron.',
    type: 'resource',
  },
]
